export const ADD_COUNTER = "ADD_COUNTER"
export const REDUCE_COUNTER = "REDUCE_COUNTER"

// ADD Action
export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE"

// GET Action
export const GET_TODO_REQUEST = "GET_TODO_REQUEST"
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"
export const GET_TODO_FAILURE = "GET_TODO_FAILURE"

export const GET_TASK_REQUEST = "GET_TASK_REQUEST"
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS"